### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by JamesMoriartyDecripto** [SocialLinks-IO/telegram-similar-channels#1]
Hi, it gives me an error:

line 30, in get_similar_channels
    result = loop.run_until_complete(safe_api_request(bot(functions.channels.GetChannelRecommendationsRequest(channel=channel)), 'get channels'))
AttributeError: module 'telethon.tl.functions.channels' has no attribute 'GetChannelRecommendationsRequest'

**Comment by muzanxdem** [comment]
Try 
`pip install --upgrade telethon`

**Comment by JamesMoriartyDecripto** [comment]
it worked, now it gives me this error, do you know what to do?

Some error, get channels: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetChannelRecommendationsRequest)
Traceback (most recent call last):
  File "search.py", line 11, in <module>
    for c in result.chats:
AttributeError: 'NoneType' object has no attribute 'chats'
